site_name: Otterdog configuration @ eclipse-oomph
site_description: Otterdog configuration @ eclipse-oomph
strict: true

site_url: https://eclipse-oomph.github.io/.eclipsefdn/

docs_dir: ./docs
site_dir: ./_site

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins: []
nav: []
watch: []
